@startuml
start
:User executes AddCommand;

if() then ([No user input error \n or missing fields])
    :Check for Duplicate Books;
    if() then ([No Duplicate Book Found])
        :Add book into Model and Storage;
        :Sort books by user's sorting preference, if any;
    else ([Duplicate Book found])
        :Produce Error Message;
    endif
else ([Input error or missing fields])
    :Produce Error Message;
endif
:Return message to user;
stop
@enduml
