@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor ALGO_COLOR
skinparam classBackgroundColor ALGO_COLOR

package Algorithm {
Class XYZAlgorithm
}

package WordBank {
Class WordBank

package WordStore {
Abstract class WordStore
Class XYZWordStore
}

package Word {
Class Word
}
}

Class HiddenOutside #FFFFFF

HiddenOutside ..> WordBank

XYZAlgorithm -> "1" WordBank
note bottom of XYZAlgorithm: XYZAlgorithm = SuggestionAlgorithm etc
WordBank "*" -down-> "1" WordStore
XYZWordStore .up.|> WordStore
note bottom of XYZWordStore: XYZWordStore = NameWordStore, GenreWordStore etc
XYZWordStore "1" -> "*" Word

@enduml
