@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title Initial state

class State1 as "__fl0:filteredList__"

class Pointer as "__b0:Harry Potter__" #FFFFF
class Pointer1 as "__b1:Hunger Games__" #FFFFF
class Pointer2 as "__b2:Cinderella__" #FFFFF

Pointer -up- State1
Pointer1 -up- State1
Pointer2 -up- State1

@end
