@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "find n/harry"

class State1 as "__fl0:filteredList__"

class Pointer as "__b0:Harry Potter__" #FFFFF
class Pointer1 as "__b1:Hunger Games__" #FFFFF
class Pointer2 as "__b2:Cinderella__" #FFFFF
Pointer1 -[hidden]left-> State1
Pointer2 -[hidden]right-> State1
hide Pointer1
hide Pointer2

Pointer -up- State1

@end
