@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyLibrary <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class Library
Class ReadOnlyLibrary
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs
Class WordBank

Package Book {
Class Book
Class Name
Class Genre
Class TotalPages
Class Bookmark
Class UniqueBookList
}

Package Tag {
Class Tag
}

package WordBank {
Class WordBank

package WordStore {
Abstract class WordStore
Class XYZWordStore
}

package Word {
Class Word
}
}
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

Library .up.|> ReadOnlyLibrary

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" Library
ModelManager o--> "1" WordBank
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

Library *--> "1" UniqueBookList
UniqueBookList o--> "*" Book
Book *--> Name
Book *--> Genre
Book *--> TotalPages
Book *--> Bookmark
Book *--> "*" Tag

WordBank "*" -down-> "1" WordStore
XYZWordStore .up.|> WordStore
note left of XYZWordStore: "XYZWordStore = NameWordStore, \n GenreWordStore etc" as N1
XYZWordStore "1" -> "*" Word

Name -[hidden]right-> Genre
Genre-[hidden]right-> TotalPages
TotalPages-[hidden]right-> Bookmark

ModelManager -->"1" Book : filtered list
@enduml
