title: "bookmark"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2021S1-CS2103T-F13-2/tp"
github_icon: "images/github-icon.png"
bookmark_icon: "images/bookmarkicon.png"

plugins:
  - jemoji
